#!/usr/bin/env bash
# Define a function to display information for a subdomain

display_subdomain_info() {
    domain="$1"
    subdomain="$2"
    record_type="$(dig +short -t A "$subdomain.$domain")"
    
    echo "The subdomain $subdomain is a $record_type record and points to $record_type"
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    default_subdomains=("www" "lb-01" "web-01" "web-02")
    for sub in "${default_subdomains[@]}"; do
        display_subdomain_info "$domain" "$sub"
    done
else
    display_subdomain_info "$domain" "$subdomain"
fi
