#!/usr/bin/env bash
# add configuration 
apt-get update
apt-get install nginx
sed -i '\%^\tlocation / {%a\ \n\t\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default
service nginx restart
