#!/usr/bin/env bash
# install HAproxy on the server and configure it send traffic to both servers
apt-get update
apt-get install haproxy
echo -e "\nfrontend cfg_front\n\tbind *:80\n\toption http\n\tdefault_backend cfg_back\nbackend cfg_back\n\tbalance roundrobin\n\tserver 374415-web-01 52.91.146.24:80 check\n\tserver 374415-web-02 54.237.94.137:80 check\n" >> /etc/haproxy/haproxy.cfg
systemctl status haproxy.service
