#!/usr/bin/env bash

# 
sudo sh -c "echo $$ > /var/run/myscript.pid"

trap  'echo "I hate the kill command"; sudo rm /var/run/myscript.pid; exit 0' SIGTERM
trap 'sudo -rm /var/run/myscript.pid; exit 0' SIGQUIT
trap  'echo "Y U no love me?!"' SIGINT

while true
do
    echo "To infinity and beyond"
    sleep 1
done
