#!/usr/bin/env bash
# create a file /var/run/myscript.pid contains its own pid
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

sudo sh -c "echo $$ > /var/run/myscript.pid"
trap  'echo "I hate the kill command"; sudo rm /var/run/myscript.pid; exit 0' SIGTERM
trap 'sudo -rm /var/run/myscript.pid; exit 0' SIGQUIT
trap  'echo "Y U no love me?!";exit 0' SIGINT
while true
do
    echo "To infinity and beyond"
    sleep 1
done