#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

sudo cp /etc/hosts ~/hosts.new
sudo sed -i '$ a\127.0.0.2 localhost' /etc/hosts
sudo sed -i '$ a\8.8.8.8 facebook.com' /etc/hosts
sudo cp -f ~/hosts.new /etc/hosts